### ISSUE TITLE
Refactor: Move 1M Qs from CoLab to code

### ISSUE THREAD

**Issue by PhilipQuirke** [PhilipQuirke/verified_transformers#1]
Part 9 of the Notebooks\VerifiedArithmeticAnalyse.ipynb "Can the model do 1 million questions without error?" contains that can be reused by other (non-Math) CoLabs. It doesnt seem to have any maths specific code

Migrate the code out of CoLab and into the QuantaTools\model_loss.py file. Pass cfg (and any other info needed) as params to the new function.

Simplify the CoLab by removing the corresponding code. Test the simplified CoLab can run the function.

Make the same simplifications to Notebooks\Accurate_Math_Analyse.ipynb

**Comment by amirabdullah19852020** [comment]
And if you can assign this ticket to me as well please.

**Comment by amirabdullah19852020** [comment]
Pull request here: https://github.com/PhilipQuirke/verified_transformers/pull/20

I'll put in a PR for the PCA issue, once this one is merged.
