### ISSUE TITLE
Improve quanta map readability by highlighting identical cells

### ISSUE THREAD

**Issue by PhilipQuirke** [PhilipQuirke/verified_transformers#16]
The quanta map graphics try to show lots of behavior or algorithm facts about the model. As models get larger, there are many cells and lots of information to absorb. For example:
https://github.com/PhilipQuirke/verified_transformers/blob/main/assets/ins1_mix_d6_l3_h4_t40K_s372001AnswerImpactBehaviorPerNode.svg

We can improve them to improve readability. This ticket covers highlighting identical cells:
- Finding vertical groupings of adjacent cells in the quanta map containing exactly the same text and with the same shade
- Drawing a one-pixel black border around the group of cells.
- Only showing the cell text once for the group

For maths, in the algorithm and attention maps, for the case where say A3.BA is implemented across 2 attention heads, this would highlight that fact. For the answer impact map, this would highlight the "vertical stripes" of the map.

**Comment by amirabdullah19852020** [comment]
I'll do this one so I can understand the Quanta maps a bit better. After this, I'll discuss if there's something substantial I can pick up for paper 3.

**Comment by PhilipQuirke** [comment]
Completed
