### ISSUE TITLE
Refactor: Move PCA code from CoLab to code 

### ISSUE THREAD

**Issue by PhilipQuirke** [PhilipQuirke/verified_transformers#2]
Part 19A/B/C of the Notebooks\VerifiedArithmeticAnalyse.ipynb relate to PCA analysis of the transformer model. They contain code that can be reused by other (non-Math) CoLabs. It code includes some maths specific code

Migrate the code out of CoLab and into new files QuantaTools\model_pca.py and QuantaTools\math_pca.py file. Pass cfg (and any other info needed) as params to the new functions. model_pca.py should contain generic code - maths_pca.py specific code any code specific to maths.

Simplify the CoLab by removing the corresponding code. Test the simplified CoLab can run the new function.

Consider making the same simplifications to Notebooks\Accurate_Math_Analyse.ipynb. Only do this if the PCA code is very similar in both.  (Accurate_Math_Analyse is historic and relates to Paper 2. At some point we will stop maintaining it.)

**Comment by amirabdullah19852020** [comment]
If you can assign this to me please.

**Comment by amirabdullah19852020** [comment]
I'll do this monday night my time.

**Comment by amir-in-a-cynch** [comment]
Got sidetracked, but I will still get to this today or tomorrow.

**Comment by amirabdullah19852020** [comment]
Partially done for parts 19 A. The automatic part may need some cleanup before it can be refactored out fully.

**Comment by PhilipQuirke** [comment]
Happy to close issue
